name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'
        check-latest: true

    - name: Build and package binaries
      run: |
        mkdir -p artifact
        platforms=("linux" "windows" "darwin" "freebsd")
        arch="amd64"

        for platform in "${platforms[@]}"; do
          if [ "$platform" == "windows" ]; then
            ext=".exe"
          else
            ext=""
          fi
          echo "Building for $platform $arch"
          GOOS=$platform GOARCH=$arch CGO_ENABLED=0 go build -o "artifact/deeplx-pro-${platform}-${arch}${ext}" -a -ldflags '-s -w -extldflags "-static"' .
          tar -czvf "artifact/deeplx-pro-${platform}-${arch}.tar.gz" -C artifact "deeplx-pro-${platform}-${arch}${ext}"
        done

    - name: Upload packaged binaries
      uses: actions/upload-artifact@master
      with:
        name: deeplx-pro-pre-built.zip
        path: artifact/*.tar.gz

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GHCR_PAT }}
      with:
        tag_name: v1.0.1
        files: artifact/*.tar.gz
              
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 1
        keep_minimum_runs: 8
